docs/architecture-decision-records/README.md
docs/architecture-decision-records/adr-001-node-and-client-id-types.md
docs/architecture-decision-records/adr-template.md

Introduce ADRs and add one on node and client IDs

---

docs/architecture-decision-records/README.md
docs/architecture-decision-records/adr-001-node-and-client-id-types.md

Accept ADR 1: String types for node and client IDs

---

pkg/deploytest/deployment.go
pkg/grpctransport/grpctransport.go

Fix hanging shutdown on some tests

---

pkg/deploytest/deployment.go

One goroutine was submitting dummy client requests
and another one was closing the connection at the end.
Now both is done in the same goroutine.
Fixes #20 

Fix race condition in deployment test

---

.github/workflows/test.yml
Makefile
mirbft_test.go
pkg/deploytest/testreplica.go

Introduce a Makefile and fix GitHub Actions

---

cmd/mircat/main.go
mirbft_test.go
pkg/crypto/pseudo.go
pkg/deploytest/deployment.go
pkg/deploytest/testreplica.go
pkg/dummyclient/dummyclient.go
pkg/eventlog/interceptor.go
pkg/grpctransport/grpctransport.go
pkg/iss/bucketgroup.go
pkg/iss/checkpoint.go
pkg/iss/config.go
pkg/iss/iss.go
pkg/iss/pbft.go
pkg/ordering/dummyprotocol.go
pkg/reqstore/volatilereqstore.go
pkg/serializing/serializing.go
pkg/types/types.go
samples/chat-demo/main.go
workers.go

Fix linter warnings

---

docs/architecture-decision-records/0002-timer-module.md

ADR 2: Timer Module

---

cmd/mircat/eventhandler.go
cmd/mircat/main.go

Mircat: Use partial event list on parsing error

---

pkg/iss/iss.go

ISS: Fix delivery order bug

---

workers.go

Fix app worker returning too early

---

pkg/clients/signingclienttracker.go

Fix bug in client tracker when logger is nil

---

pkg/grpctransport/grpctransport.go

This PR fixes https://github.com/filecoin-project/mir/issues/45.

Replace splitAddrPort by SplitHostPort

---

pkg/crypto/api.go

Update Crypto interface doc.

---

pkg/grpctransport/grpctransport.go

This PR adds a check whether a connection is `nil` before closing it.

Check connections before accessing them

---

node.go
pkg/crypto/defaultimpl.go
pkg/net/grpc/grpctransport.go
pkg/types/types.go
samples/chat-demo/main.go

Remove some misleading comments from the past

---

samples/chat-demo/main.go

Fixes a bug introduced in #133.
Will merge without a review.

Hotfix chat-demo

---

pkg/logging/decorator.go
pkg/logging/logger.go
pkg/logging/synchronizer.go

I will need this functionality for `pkg/deploytest` refactoring.

Add IsConcurrent to the logger interface

---

pkg/deploytest/testreplica.go
pkg/requestreceiver/requestreceiver.go
samples/chat-demo/main.go

Remove hardcoded dependencies of RequestReceiver on ISS.

De-ISS-ize RequestReceiver

---

pkg/iss/iss.go
pkg/iss/pbftsegmentchkp.go
pkg/iss/pbftviewchange.go
pkg/iss/pbftviewchangestate.go
pkg/util/maputil/maputil.go

Tiny technical change (code cleanup), merging without review.

Move sorted map iteration function to maputil

---

pkg/mempool/dsl/dsl.go

Minor fix. Will merge without a review.

Add missing field to the origin field in mempool dsl wrappers

---

samples/chat-demo/app.go

Remove new epoch notifications from chat

---

pkg/iss/epochinfo.go

Addresses the immediate cause of #203 .
There might be, however, a deeper cause of that issue, so keeping that issue open.

Fix bug in ISS SB message validation

---

pkg/availability/batchdb/fakebatchdb/fakebatchdb.go

Fix the bug when fakebatchdb sent multiple replies to a lookup request

---

pkg/deploytest/testreplica.go
pkg/eventlog/interceptor.go

This PR adds a mechanism to open a file on recorder creation and close the recorder file via Stop function.

Improve recorder io

---

pkg/deploytest/simtransport.go
pkg/deploytest/simulation.go

Fix simulation segfaults

---

eventbuffer.go

Related to the [PR comment about input sanitization](https://github.com/filecoin-project/mir/pull/230#discussion_r985320451).
Trivial change, merging without review.

Drop messages with non-existent destination module

---

pkg/systems/smr/system.go

The chat demo was broken on the main branch.

Temporarily disable address checking in SMR system

---

pkg/net/libp2p/libp2p_transport.go

Will merge without a review since we found this together with Matej!

Change log level on send error

---

cmd/bench/cmd/app.go
cmd/bench/cmd/node.go
cmd/mircat/debug.go
pkg/batchfetcher/batchfetcher.go
pkg/checkpoint/checkpoint.go
pkg/iss/iss.go
pkg/iss/protobufs.go
pkg/systems/smr/applogic.go
pkg/systems/smr/appmodule.go
pkg/systems/smr/reconfigappwrapper.go
pkg/systems/smr/smr_test.go
pkg/systems/smr/system.go
pkg/types/types.go
samples/chat-demo/app.go
samples/chat-demo/main.go

Resolves #248 .
Resolves #276 .

Start node from arbitrary checkpoint

---

pkg/types/types.go

added function Bytes() to all types that return their serialization in a []byte slice.
Closes #35

added Bytes() to all types (Closes #35) 

---

node.go

ActiveModule's ApplyEvents function receives a context and is supposed to be non-blocking.
When a node is stopping, canceling the context
signals the module implementation to abort any processing.

Cancel event processing context on node shutdown

---

cmd/mircat/main.go

Fix mircat selection args misprinting

---

samples/chat-demo/app.go
samples/chat-demo/main.go

Use dummy crypto and libp2p addresses in chat demo

---

pkg/iss/iss.go

Update leader policy on state transfer

---

pkg/clientprogress/clientprogress.go
pkg/clientprogress/deliveredrequests.go
pkg/iss/iss.go

Fix small issues with log messages

---

cmd/mircat/customtransform.go
cmd/mircat/display.go

Enable custom event transformation in mircat

---

pkg/net/libp2p/remoteconnection.go
pkg/net/libp2p/transport.go
pkg/net/libp2p/transport_test.go

This PR adds a test that simulates messaging in a network with ten nodes and adding five new nodes.

libp2p mesh tests

---

pkg/checkpoint/certificate.go
pkg/checkpoint/checkpoint.go
pkg/orderers/segment.go
pkg/util/maputil/maputil.go

Inspired by #348 by @ranchalp 's implementation.

Simplify maputil.Transform to use a single func

---

pkg/clientprogress/clientprogress.go

Simplify loading ClientProgress from Protobufs

---

pkg/iss/iss.go

Technically, this could be made redundant, since it is the same checkpoint the application is restoring from. However, it helps preserve the pattern of calls to the application where a checkpoint is explicitly delivered in each epoch.

Explicitly deliver checkpoint when restoring state

---

pkg/batchfetcher/batchfetcher.go
pkg/iss/iss.go
pkg/orderers/pbftslot.go
pkg/orderers/pbftviewchange.go

Fix to #335 after decision (not to wait for timeout) and after rebasing with latest PRs.

Fix to #335

---

pkg/batchfetcher/batchfetcher.go

Add forgotten epoch number update in batch fetcher

---

pkg/batchfetcher/batchfetcher.go

If the batch fetcher received transactions from the availability module in a different order than the order in which they should be delivered, it could happen that the deduplication code removed the transactions from the wrong batches.
This is now fixed by performing deduplication immediately before delivery instead of upon the reception of transaction payloads from the availability module.

Fix transaction deduplication bug in batch fetcher

---

pkg/batchfetcher/batchfetcher.go
pkg/batchfetcher/events/events.go

Rebase and merge this after #382 is merged.

Minor cleanup

---

pkg/availability/multisigcollector/internal/parts/batchreconstruction/batchreconstruction.go
pkg/availability/multisigcollector/internal/parts/certcreation/certcreation.go
pkg/availability/multisigcollector/internal/parts/certverification/certverification.go
pkg/availability/multisigcollector/multisigcollector.go
pkg/checkpoint/protocol.go
pkg/orderers/orderer.go
pkg/orderers/pbftviewchange.go
pkg/util/sliceutil/sliceutil.go
samples/availability-layer-demo/client.go

Fixes part of #384 (but sill work to do there, do not close issue until fixed for ISS too):

Verify senders and signers are part of membership 

---

pkg/bcb/bcbmodule.go
pkg/dsl/dslmodule.go
pkg/dsl/test/dslmodule_test.go

State update handlers in DSL module

---

cmd/bench/cmd/node.go
pkg/deploytest/localcrypto.go
pkg/deploytest/localgrpctransport.go
pkg/deploytest/locallibp2ptransport.go
pkg/deploytest/localtransport.go
pkg/iss/iss.go
pkg/orderers/orderer.go
pkg/orderers/pbftviewchange.go
pkg/orderers/pbftviewchangestate.go
pkg/orderers/segment.go
pkg/trantor/smr_test.go

Replace panic by errors

---

cmd/mircat/nulltransport.go
pkg/deploytest/faketransport.go
pkg/deploytest/simtransport.go
pkg/net/grpc/grpctransport.go
pkg/net/libp2p/transport.go
pkg/net/libp2p/transport_test.go
pkg/net/transport.go

Add error return value to waiting for connections

---

codegen/generator.go
codegen/generators/mir-std-gen/generator/generator.go
codegen/generators/types-gen/generator/generator.go
go.mod
samples/chat-demo/main.go

This PR fixes **semgrep** linter findings.

Fix linter findings

---

pkg/orderers/internal/common/common.go
pkg/orderers/internal/parts/goodcase/pbftgoodcase.go
pkg/orderers/internal/parts/viewchange/pbftviewchange.go

Fix bug with `inViewChange` PBFT state variable.

---

pkg/checkpoint/checkpoint.go

This is a DIRTY DIRTY hack. It works around the problem of protocol buffers not distinguishing between an empty slice and a nil value (both get serialized to the same bytes and deserialized to nil). CBOR, however does make this distinction. The checkpoint data structure does contain slices that may be empty
(DeliveredTXs inside ClientProgress). Thus, if a checkpoint were directly serialized locally, and the very same checkpoint transmitted to another node (which implies protobuf marshalling and unmarshalling) and serialized there, the two outputs (local and remote) would not be the same (an empty slice locally and nil on the remote node). To keep the serialization consistent, we always perform a protobuf marshalling-unmarshalling of the checkpoint. Note that we cannot use the protobuf …

Work around protobuf/CBOR serialization issue

---

node.go
nodestats.go
stopwatch.go
workers.go

Btw, no I'm not coding this fast, I wrote this to debug my old Trnator benchmarks and now I'm just porting it to the proper code base.

Add module processing times to Node stats

---

pkg/availability/multisigcollector/multisigcollector.go

This can be un-done when #495 is fixed.

Disable availability certificate batching by defualt

---

samples/pingpong/run.sh

Add a simple script to run two pingpong nodes in tmux.

Add run.sh to pingpong for convenience

---

frontend/index.css
frontend/index.html

Create frontend to connect to MIR nodes to accept or decline new logs. See attached images for examples.
The MIR nodes should run on port 8080+<membership number>
Use cases:
1) Connecting to non-existing ws port
2) Connecting to existing ws port and starting to receive log messages
3) Clicking on 'Decline' -> decline the incoming log message and receive the new log message
4) Clicking on 'Accept' -> accept the incoming log message and store it in "Accepted Logs" and receive the new log message

Create frontend to connect to MIR nodes to accept or decline new logs

---

frontend/index.css
frontend/index.html

Converted the Accepted Logs list into a stack with the most recent message on top and added a border around each accepted message

Frontend ~ Stacked log

---

pkg/debugger/websocketwriter.go

Changed the waiting connection message of the debugger from "No Connection" to "Waiting for interface connection to proceed"

Debugger ~ No connection message
