consensus-shipyard/mir

pkg/deploytest/deployment.go, pkg/deploytest/testreplica.go, pkg/grpctransport/grpctransport.go
The transport layer is writing messages that it receives over the
network to a channel, from which the node implementation reads them.
When the node is shutting down, it stops reading incoming messages from
this channel. However, if there are still incoming messages on the wire
at that time, the transport layer tries to write them to the channel and
blocks (since nobody reads any more). This prevented a clean shutdown of
the transport layer.
Now the connecting node explicitly cancels the context of the connection
when disconnecting and the node being connected uses a select statement,
waiting for this event alongside trying to write the message to the
processing channel.
Fixes #36
=> Fix hanging transport layer shutdown in tests

.github/workflows/test.yml
Note that this action does not simply run the `make lint` command.
We directly use the `golangci-lint` GitHub Action that also creates
annotations in GitHub with the found problems.
The `make lint` command present is still supported though
for easy local linting.
=> Add lint GitHub Action

pkg/iss/iss.go
The total number of replicas does not have to be exactly 3f+1 for some
natural number f. Fix the helper functions to calculate strong and
weak Byzantine quorums such that they give correct result in any case.
=> ISS: Fix quorum sizes for any n > 3f

pkg/iss/iss.go
This pull request fixes a memory leak in the ISS state.
=> ISS: Clean up delivered commit log entries

pkg/iss/config.go, pkg/iss/iss.go
This pull request fixes a bug introduced in c01d2e8 which broke `ISS.epochFinished` and resolves #2. It also adjusts the default ISS configuration such that there is at least one integration test that has to order requests across multiple epochs.
=> Fix transitioning into new epoch

README.md
This PR adds a badge on the top of README file that shows the number of alerts detected by [LGTM analysis](https://lgtm.com/help/lgtm/about-lgtm).
=> Add LGTM badge to README

docs/architecture-decision-records/0003-generalize-modules.md
=> Module generalization

.github/workflows/codeql-analysis.yml, README.md, pkg/crypto/pseudo.go, pkg/iss/config.go
GitHub Code Scanning [can use the same mechanism as LGTM.com](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql). Switch into using GitHub Code Scanning.
=> Replace LGTM with GitHub Code Scanning

mir_test.go
The code in `runIntegrationWithISSConfig` expects the deployment directory under the system temporary directory. Create the test deployment directory there if the test config specifies it explicitly. Moreover, ensure the directory gets removed when the test is over.
=> Fix creating and removing pre-defined test deployment directory

pkg/iss/checkpoint.go, pkg/iss/config.go, pkg/iss/iss.go, pkg/iss/pbftgoodcase.go, pkg/iss/pbftsegmentchkp.go, pkg/iss/pbftviewchange.go, pkg/iss/pbftviewchangestate.go
The only one that was still missing was the checkpoint message.
The rest is either not critical for correctness or already being re-transmitted.
This is just the minimal modification to guarantee correctness of the protocol. Even some non-critical protocol messages might be periodically re-transmitted to avoid view changes in certain cases, but that is future work for another PR.
=> Keep resending critical messages in ISS

.golangci.yaml
For some reason, the linter works fine within the timeout in PRs, but not in the main branch. Will try to increase the timeout to fix CI builds in main.
=> Increase the timeout for linter in CI

pkg/crypto/defaultimpl.go, pkg/net/libp2p/libp2ptransport.go
This PR fixes several bugs found by `semgrep` run with the following commands:
- `semgrep --config "p/semgrep-go-correctness" ./`
- `semgrep --config "p/trailofbits" ./`
=> Fix semgrep linting errors

.golangci.yaml, cmd/mircat/debug.go, cmd/mircat/display.go, cmd/mircat/eventloader.go, pkg/crypto/ecdsa.go, pkg/deploytest/testreplica.go, pkg/eventlog/interceptor.go, pkg/iss/iss.go, pkg/modules/mockmodules/mock_modules.go, pkg/pb/eventpb/eventpb.pb.mir.go, samples/chat-demo/main.go
This PR enables several new linters, adds a setting for `goimport` linter to enforce the order of the project's packages, and also fixes the found bugs by the introduced linters.
=> Enable new linters and fix found bugs

pkg/dsl/dslmodule.go
Most modules don't need to do anything on Init and the philosophy
of DSL modules is to avoid mixing protocol logic with boilerplate.
Hence, it makes sense to avoid writing an empty handler for init
for each DSL module and just make processing this event optional.
=> Make Init event optional in DSL modules

pkg/availability/multisigcollector/internal/common/common.go, pkg/availability/multisigcollector/internal/parts/certcreation/certcreation.go, pkg/availability/multisigcollector/internal/parts/certverification/certverification.go, pkg/availability/multisigcollector/multisigcollector.go
It is sufficient to store the data on F+1 nodes in order for it to be retrievable.
=> Collect F+1 instead of (N+F)/2+1 signatures in multisigcollector

pkg/availability/multisigcollector/internal/common/common.go, pkg/mempool/simplemempool/internal/common/common.go, pkg/mempool/simplemempool/internal/parts/computeids/computeids.go, pkg/mempool/simplemempool/internal/parts/formbatches/formbatches.go, pkg/mempool/simplemempool/internal/parts/lookuptxs/lockuptxs.go, pkg/mempool/simplemempool/simplemempool.go
The prototype expects that new transactions will be delivered to it by means of `NewRequests` events and stores them in an in-memory map. It uses hashes for transaction and batch IDs. 
To support crash-recovery, persistent storage should be added for the transactions.
=> Simple mempool module prototype

pkg/mempool/simplemempool/internal/parts/formbatches/formbatches.go
The current implementation didn't properly count the number of transactions added to the batch.
When there was only one transaction in the mempool, the counter `i` would always keep the value 0 and `newTxIDs` was not trimmed properly.
=> Fix transaction counting bug in simple mempool

pkg/types/moduleid.go, pkg/types/types.go, workitems.go
In preparation for submodules in Mir this commit introduces structured
module IDs. They are backwards-compatible with the old unstructured
ones, which are considered to be identifiers of top-level modules.
=> Add hierarchical module IDs

Makefile
If the generated protobufs are broken (e.g. during a git rebase), running `make generate` used to return an error, because it tried to compile them first with Go. Now the `./protos` are generated first.
=> Generate protobufs first

pkg/deploytest/simtimer.go, pkg/events/events.go, pkg/iss/checkpoint.go, pkg/iss/iss.go, pkg/iss/sbeventservice.go, pkg/simplewal/simplewal.go, pkg/timer/timer.go, pkg/types/types.go
Having a separate type for the retention index for each module
seems like over-engineering, given that they are all used
exactly the same way.
I used the IDE to automatically rename everything.
=> Unify retention index type

pkg/dsl/dslmodule.go
This is useful for modules that perform processing only on some events.
E.g., the default action could be forwarding to another module.
=> Add default handler registration to DSL module

pkg/availability/multisigcollector/multisigcollector.go, pkg/iss/iss_test.go, samples/chat-demo/main.go
=> Encapsulate multisig collector factory in a func

cmd/bench/cmd/node.go, cmd/mircat/debug.go, config.go, eventbuffer.go, node.go, node_test.go, pkg/deploytest/deployment.go, pkg/events/eventlist.go, samples/availability-layer-demo/client.go, samples/bcb-demo/client.go, samples/chat-demo/main.go
This PR implements backpressure for event processing within a node.
Active modules now cannot make the node's event buffers explode in size, as the node stops reading input from active modules when its internal event buffer grows above a configurable limit.
The limit on the internal event buffer is a "soft limit" in the sense that as long as there are fewer events than the limit in the buffer, an arbitrary event list can be added, which might result in the buffer's actual size "overshooting" the limit, if the event list being added is long. This should not be a big problem in practice though, as the list already occupies space in memory and the events are simply "moved" to the buffer, without creating another copy.
Resolves #100 .
Resolves #238 .
=> Event backpressure

pkg/systems/smr/system.go
Fix multiaddr comparison. There was a bug because `addr` and `t.nodeAddress` were consider of different types.
=> hotfix: multiaddr comparison

pkg/net/libp2p/libp2p_transport.go, pkg/net/libp2p/libp2p_transport_test.go, pkg/systems/smr/system.go
Also, don't wait for all nodes to be connected in SMR system.
=> Fix locking bug in libp2p transport

cmd/bench/cmd/node.go, cmd/bench/stats/stat-interceptor.go, pkg/checkpoint/protocol.go, pkg/iss/config.go, pkg/mempool/simplemempool/simplemempool.go, pkg/systems/smr/params.go, pkg/systems/smr/system.go, pkg/util/libp2p/libp2p.go, samples/chat-demo/main.go
Make the SMR system configurable at instantiation.
=> SMR parameters

pkg/batchfetcher/batchfetcher.go, pkg/net/libp2p/params.go
Padding blocks (resulting from view changes) have been ignored and not delivered to the application at all, which was confusing the application with respect to checkpoints (it expects to receive a certain number of blocks between checkpoints).
We now deliver empty blocks on reception of such padding certificates.
=> Deliver padding blocks

pkg/threshcrypto/threshcrypto.go
When operations succeed, `err` is `nil`, and the module would panic when trying to call `err.Error()`
=> threshcrypto: Don't panic when no errors occur

pkg/deploytest/simulation.go, pkg/modules/eventprocessing.go, pkg/threshcrypto/threshcrypto.go
I accidentally sent `SendMessage` events to the threshcrypto module and got a cryptic error message.
This PR fixes error propagation in `ApplyEventsConcurrently`, and aborts simulations when modules produce errors.
Aborting sounds like the appropriate behavior because right now the error I described (sending events to the wrong module) will just quietly exit the simulated process and hang the test until it timeouts.
=> Improve module error propagation

pkg/crypto/pseudo.go, pkg/deploytest/localcrypto.go
Let's explicitly say that the function is not secure.
=> Explicitly describe that the function is insecure and intended for testing

pkg/eventmangler/eventmangler.go, pkg/systems/smr/system.go
The event mangler module can drop and randomly delay events with a configurable drop rate and interval of possible delays. The events that are not dropped are forwarded to a module specified in the event mangler configuration.
This is useful for, for example, simulating a flaky network.
Resolves #240
=> Implement event mangler module

pkg/eventlog/recorder.go
Avoid nil dereference if Intercept is called on a nil *Recorder and simply do nothing. This can happen if a pointer type to *Recorder is assigned to a variable with the interface type Interceptor. Mir would treat that variable as non-nil,
thinking there is an interceptor, and call Intercept() on it. For more explanation, see
https://mangatmodi.medium.com/go-check-nil-interface-the-right-way-d142776edef1
=> Work around Interceptor nil comparison (Go quirk)

cmd/mircat/custommodule.go, cmd/mircat/customtransform.go, cmd/mircat/display.go, cmd/mircat/main.go
This messes up the `mircat` code even more, but it adds a useful functionality of being able to manually create a module and pass selected events from a trace just to that module.
The `mircat` code needs a very big overhaul, but this PR is not meant to address it.
=> Add rudimentary single-module debugging to mircat

pkg/factorymodule/factory.go
A small fix to #369.
Fixing the formatting according to [go guidelines](https://tip.golang.org/doc/comment) and fixing the description of the message buffering.
=> Fix factory module docs

pkg/mempool/simplemempool/internal/common/common.go, pkg/mempool/simplemempool/internal/parts/formbatchesext/formbatches.go, pkg/mempool/simplemempool/internal/parts/formbatchesint/formbatches.go, pkg/mempool/simplemempool/simplemempool.go
The SimpleMempool gets a new (function-type) parameter. It can be set to a function that returns a list of transactions, in which case the mempool will use this function
to obtain transactions externally.
=> External transaction fetcher for mempool

pkg/net/libp2p/remoteconnection.go
Previously, if an error occurred while sending a message in the libp2p transport, the module dropped the message and tried to reconnect. If messages were very sparse and the other side of the connection gave up receiving after some time after each incoming connection, all messages would get lost.
Now, if the libp2p transport fails to send a message, it does not drop it, but instead tries to reconnect and, if reconnection succeeds, immediately re-tries to send the same message until it is sent successfully.
=> Stubborn message sending in libp2p transport

node.go
This PR adds printing log messages related to starting and finishing modules. The log level is INFO. That can be changed in the future to DEBUG.
=> Print info related to starting and finishing modules

cmd/bench/stats/stat-interceptor.go, node.go, pkg/eventlog/interceptor.go, pkg/eventlog/multiinterceptor.go
Since the Interceptor is an interface type, it can happen that a nil value of a concrete type is used in the node and, consequently, Intercept() will be called on nil. The implementation of the concrete type thus must make sure that calling Intercept even on the nil value does not cause any problems.
For more explanation, see https://mangatmodi.medium.com/go-check-nil-interface-the-right-way-d142776edef1
Fixes #326
=> Make sure Interceptor works even if it is nil

pkg/availability/multisigcollector/internal/parts/certverification/certverification.go
During testing I noticed this bug. When processing the NodeSigsVerified event, if they are not `allOk` the request is replied to, deleted, but the handler does not return, leading to a nil deref when acessing the now-deleted request.
=> multisigcollector: Fix nil deref

pkg/iss/iss.go
This fixes an issue where an invalid availability certificate that has been delivered made it (with data truncated to an empty byte slice) all the way to batch reconstruction and made the system fail. The system did not recognize it as empty, because the aborted flag was false.
=> Abort faulty availability certificates

config.go, eventbuffer.go, node.go, node_test.go, nodestats.go, pkg/deploytest/deployment.go, pkg/deploytest/helpers.go
This is more important than it might seem. When testing performance of a Mir-based system, the system is pushed to the limit, event buffers actually get full and external event processing often needs to be paused. Information on the buffer states and processed events brings a lot of insight.
=> Log basic information about event processing in Mir Node

pkg/util/maputil/maputil.go
This is not used yet, but will be in the benchmarking code.
=> Generalize selecting any key/value from maps

node.go, nodestats.go
This is only to enforce a clean shutdown of a node.
=> Wait for stat monitor goroutine

pkg/util/indexedlist/indexedlist.go, pkg/util/indexedlist/indexedlist_test.go, pkg/util/indexedlist/iterator.go
Data structure needed by the new mempool implementation (in a separate PR) so that it does not drop transactions at epoch boundaries.
=> Indexed list

pkg/net/libp2p/remoteconnection.go
This was a cause of the networking module very easily dropping messages under load.
=> Update libp2p dependency

cmd/bench/stats/stat-interceptor.go, node.go, pkg/eventlog/eventwriter.go, pkg/eventlog/eventwritergzip.go, pkg/eventlog/eventwritersqlite.go, pkg/eventlog/interceptor.go, pkg/eventlog/multiinterceptor.go, pkg/eventlog/newfilepolicy.go, pkg/eventlog/recorder.go, pkg/eventlog/recorderopts.go, workers.go
Different functions now return an EventList or an EventRecord such that the Events intercepted by the intercepter can also be modified by it.
may want to check my modifications of the implementations of the following to check nothing is broken unintentionally, as I might have overlooked something:
- type Interceptor in pkg/eventlog/interceptor.go 
- and type EventWriter in pkg/eventlog/eventwriter.go
=> modified existing functions to return an EventList for the modified interceptor for visualization

cmd/bench/cmd/client.go, cmd/bench/cmd/node.go, cmd/bench/cmd/params.go, codegen/generators/dsl-gen/generator/events.go, codegen/model/types/field.go, frontend/index.html, node_test.go, pkg/availability/multisigcollector/internal/parts/certverification/certverification.go, pkg/batchfetcher/batchfetcher.go, pkg/bcb/bcbmodule.go, pkg/checkpoint/serializing_fuzz_test.go, pkg/debugger/debugger.go, pkg/debugger/websocketwriter.go, pkg/deploytest/localtransport.go, pkg/dsl/events.go, pkg/dsl/test/dslmodule_test.go, pkg/eventlog/recorder.go, pkg/iss/iss.go, pkg/mempool/simplemempool/internal/parts/formbatchesint/formbatches.go, pkg/net/libp2p/transport_test.go, pkg/orderers/internal/parts/catchup/catchup.go, pkg/trantor/testing/smr_test.go, pkg/util/indexedlist/indexedlist_test.go
I added the necessary code to be able to replace an event with one that is sent from the frontend.
protojson.unmarshal only works if the  value types in the new event all match the ones from original event, else an error is returned.
I had to use protojson for both the mashalling and unmarshalling, for it to work correctly. Thus, the format of the message sent to the frontend has changed, messing with the display of the event in the HTML file. Instead of displaying a structured tree where only the leaves can be modified, it now appears as a single string that can be modified in its entirety.
=> replace functionality - backend

frontend/index.css, frontend/index.html
**NOTE, Merge first the pull request: https://github.com/filecoin-project/mir/pull/527**
Added the possibility to modify the logs that each MIR node sends by modifying the incoming message. (For now, only the JSON leaves are modifiable. )
All the JSON types have been taken care of:
- it's important to notice that once a 'null' field is clicked to modify, it will become a 'string type afterward'. 
- For other types, the type will be preserved if the newly modified value is acceptable for that specific type. For example, inserting 'true' into a boolean field will remain a boolean, but using 'tru' will result in it becoming a string field.
Modifiable incoming log (highlighted by the border line):
Once clicked it becomes editable as a string:
By clicking '**Replace**' the modified version …
=> Frontend ~ editable text

frontend/index.css, frontend/index.html
**NOTE, Merge first the pull request: https://github.com/filecoin-project/mir/pull/527**
Add the 'close button' that once clicked will close the connection to the MIR node (Any current Incoming Log message will be declined by default)
The new button:
Once the 'Close Connection' button is clicked, the waiting incoming log will be declined and the connection to the MIR node closed:
=> Frontend ~ close button

frontend/index.css, frontend/index.html
**NOTE, Merge first the pull request: https://github.com/filecoin-project/mir/pull/527**
Add the possibility to automatically accept the incoming logs from the MIR node when 'Sync' option selected:
By default, we are using the 'Sync' mode where we are waiting for the user input (Accept/Decline):
When changing the toggle, we will go to 'Async' mode where the incoming logs will be accepted by default:
=> Frontend ~ sync switch
